## 3.7 反復処理

```{r}
library(tidyverse)
```

### 3.7.1 指定した回数→1次元データ

```{r}
f1 <- function(x) {
  tmp <- runif(x)
  mean(tmp)
}

f1(10)           # 動作確認
#> [1] 0.5776604 # 結果の例
```

```{r}
replicate(n = 3, expr = f1(10))
#> [1] 0.4672766 0.4712016 0.5579449
```

```{r}
rep(x = f1(10), times = 3)
#> [1] 0.481329 0.481329 0.481329
```

### 3.7.2 1次元データ→1次元データ

```{r}
v <- c(5, 10, 100)
v %>% map_dbl(f1)
#> [1] 0.4857329 0.5322183 0.5084124
```

```{r}
rep(x = 10, times = 3) %>% map_dbl(f1)
# 結果は割愛
```

### 3.7.3 1次元データ→データフレーム

```{r}
f2 <- function(n) {
  tmp <- runif(n)
  list(x = n,
       p = mean(tmp),
       q = sd(tmp))
}

f2(10) # 動作確認
#> $x
#> [1] 10
#>
#> $p
#> [1] 0.6840032 （平均の例）
#>
#> $q
#> [1] 0.3750788 （標準偏差の例）
```

```{r}
v <- c(5, 10, 100)
v %>% map_dfr(f2)
#>       x     p     q
#>   <dbl> <dbl> <dbl>
#> 1     5 0.560 0.320
#> 2    10 0.559 0.271
#> 3   100 0.507 0.283
```

### 3.7.4 データフレーム→データフレーム

```{r}
f3 <- function(x, y) {
  tmp <- runif(x, min = 1,
                  max = y + 1) %>%
    as.integer
  list(x = x,
       y = y,
       p = mean(tmp),
       q = sd(tmp))
}

f3(x = 10, y = 6) # 動作確認
#> $x
#> [1] 10
#>
#> $y
#> [1] 6
#>
#> $p
#> [1] 3.2 （平均の例）
#>
#> $q
#> [1] 1.316561 （標準偏差の例）
```

```{r}
my_df <- data.frame(
  x = c(5, 10, 100,  5, 10, 100),
  y = c(6,  6,   6, 12, 12,  12))

my_df %>% pmap_dfr(f3)
#>       x     y     p     q
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     5     6  3     1.41
#> 2    10     6  3     1.49
#> 3   100     6  3.57  1.78
#> 4     5    12  7.6   5.22
#> 5    10    12  5.7   3.77
#> 6   100    12  6.36  3.59
```

### 3.7.5 補足：反復処理の並列化

```{r}
library(furrr)
plan(multisession) # 準備

v <- c(5, 10, 100)
v %>% future_map_dbl(f1, .options =
  furrr_options(seed = TRUE))
# 結果は割愛
```

