## 3.5 1次元データの（非）類似度

### 3.5.1 ユークリッド距離

```{r}
A <- c(3,   4,  5)
B <- c(3,   4, 29)
C <- c(9, -18,  8)
AB <- B - A
AC <- C - A

sum(AB^2)^0.5
#> [1] 24

sum(AC^2)^0.5
#> [1] 23
```

### 3.5.2 マンハッタン距離

```{r}
sum(abs(AB))
#> [1] 24

sum(abs(AC))
#> [1] 31
```

### 3.5.3 コサイン類似度

```{r}
sum(A * B) /
  sum(A * A)^0.5 / sum(B * B)^0.5
#> [1] 0.8169679

sum(A * C) /
  sum(A * A)^0.5 / sum(C * C)^0.5
#> [1] -0.03265116
```

### 3.5.4 相関係数

```{r}
cor(A, B)
#> [1] 0.8824975

cor(A, C)
#> [1] -0.03266277
```

#### 3.5.4.1 データフレームを使う方法

```{r}
library(tidyverse)



my_df <- data.frame(
  x = c(3,  3,   9),
  y = c(4,  4, -18),
  z = c(5, 29,   8),
  row.names = c("A", "B", "C"))

# ユークリッド距離
my_df %>% proxy::dist("Euclidean")
#>    A  B
#> B 24
#> C 23 31


# マンハッタン距離
my_df %>% proxy::dist("Manhattan")
#>    A  B
#> B 24
#> C 31 49


# コサイン類似度
my_df %>% proxy::simil("cosine")
#>             A           B
#> B  0.81696786
#> C -0.03265116  0.29342441


# 相関係数
my_df %>% proxy::simil("correlation")
#>             A           B
#> B  0.88249750
#> C -0.03266277  0.44124132
```

