## 3.3 コレクション

### 3.3.1 1次元データ

```{r}
x <- c("foo", "bar", "baz")
```

```{r}
length(x)
#> [1] 3
```

```{r}
x[2]
#> [1] "bar"
```

```{r}
x[2] <- "BAR"
x # 結果の確認
#> [1] "foo" "BAR" "baz"

x[2] <- "bar" # 元に戻す．
```

```{r}
x[-2]
#> [1] "foo" "baz"
```

```{r}
c(x, "qux")
#> [1] "foo" "bar" "baz" "qux"
```

```{r}
x <- c(x, "qux")
x # 結果の確認
#> [1] "foo" "bar" "baz" "qux"
```

#### 3.3.1.1 等間隔の数値からなる1次元データ

```{r}
1:5
#> [1] 1 2 3 4 5
```

```{r}
seq(from = 0, to = 10, by = 2)
#> [1]  0  2  4  6  8 10
```

```{r}
seq(from = 0, to = 1, by = 0.5)
#> [1] 0.0 0.5 1.0
```

```{r}
seq(from = 0, to = 100, length.out = 5)
#> [1]   0  25  50  75 100
```

```{r}
rep(x = 10, times = 5)
#> [1] 10 10 10 10 10
```

#### 3.3.1.2 ファクタ（Rのみ）

```{r}
tmp <- c("グー", "パー", "グー", "パー")
x <- factor(tmp, levels = c("グー", "チョキ", "パー"))
x
#> [1] グー パー グー パー
#> Levels: グー チョキ パー
```

### 3.3.2 数値計算やデータ解析用の1次元データ

```{r}
x <- c(2, 3, 5, 7)

x + 10 # 加算
#> [1] 12 13 15 17

x * 10 # 乗算
#> [1] 20 30 50 70
```

```{r}
x <- c(2, 3)
sin(x)
#> [1] 0.9092974 0.1411200
```

```{r}
x <- c(2,  3,   5,    7)
y <- c(1, 10, 100, 1000)
x + y
#> [1]    3   13  105 1007

x * y
#> [1]    2   30  500 7000
```

```{r}
sum(x * y)
#> [1] 7532
```

```{r}
x <- c(TRUE, FALSE)
y <- c(TRUE, TRUE)
x & y
#> [1]  TRUE FALSE
```

#### 3.3.2.1 1次元データ同士の比較

```{r}
u <- c(1, 2, 3)
v <- c(1, 2, 3)
w <- c(1, 2, 4)

identical(u, v) # 全体の比較
#> [1] TRUE

identical(u, w) # 全体の比較
#> [1] FALSE

u == v          # 要素ごとの比較
#> [1] TRUE TRUE TRUE

u == w          # 要素ごとの比較
#> [1]  TRUE  TRUE FALSE
```

```{r}
sum(u == w)  # 同じ要素の数
#> [1] 2

mean(u == w) # 同じ要素の割合
#> [1] 0.6666667
```

### 3.3.3 複数種類のデータをひとまとめにする

```{r}
x <- list(1, "two")
```

```{r}
x[[2]]
#> [1] "two"
```

### 3.3.4 文字列と値のペアのコレクション

```{r}
x <- list("apple"  = "りんご",
          "orange" = "みかん")
```

```{r}
x[["grape"]] <- "ぶどう"
```

```{r}
x$apple
# あるいは
x$"apple"
# あるいは
x[["apple"]]
# あるいは
tmp <- "apple"
x[[tmp]]

#> [1] "りんご"
```

### 3.3.5 補足：コピーと参照

```{r}
x <- c("foo", "bar", "baz")
y <- x
y[2] <- "BAR" # yを更新する．
y
#> [1] "foo" "BAR" "baz"

x             # xは変わらない．
#> [1] "foo" "bar" "baz"
```

