## 5.2 データの変換

### 5.2.1 標準化

```{r}
x1 <- c(1, 2, 3)

z1 <- scale(x1)
# あるいは
z1 <- (x1 - mean(x1)) / sd(x1)

z1
#> [1] -1  0  1
```

```{r}
c(mean(z1), sd(z1))
#> [1] 0 1
```

```{r}
z1 * sd(x1) + mean(x1)
#> [1] 1 2 3
```

```{r}
x2 <- c(1, 3, 5)
z2 <- (x2 - mean(x1)) / sd(x1)
c(mean(z2), sd(z2))
#> [1] 1 2
```

### 5.2.2 ワンホットエンコーディング

```{r}
library(caret)
library(tidyverse)

my_df <- data.frame(
  id = c(1, 2, 3),
  class = as.factor(
    c("A", "B", "C")))

my_enc <- my_df %>%
  dummyVars(formula = ~ .)

my_enc %>% predict(my_df)
#>   id class.A class.B class.C
#> 1  1       1       0       0
#> 2  2       0       1       0
#> 3  3       0       0       1
```

```{r}
my_df2 <- data.frame(
  id =    c( 4 ,  5 ,  6 ),
  class = c("B", "C", "B"))
my_enc %>% predict(my_df2)
#>   id class.A class.B class.C
#> 1  4       0       1       0
#> 2  5       0       0       1
#> 3  6       0       1       0
```

#### 5.2.2.1 補足：冗長性の排除

```{r}
my_enc <- my_df %>%
  dummyVars(formula = ~ .,
            fullRank = TRUE)
my_enc %>% predict(my_df)
#>   id class.B class.C
#> 1  1       0       0
#> 2  2       1       0
#> 3  3       0       1

my_enc %>% predict(my_df2)
#>   id class.B class.C
#> 1  4       1       0
#> 2  5       0       1
#> 3  6       1       0
```

