## 4.3 乱数

### 4.3.1 一様乱数（離散）

```{r}
x <- sample(x = 1:6,        # 範囲
            size = 10000,   # 乱数の数
            replace = TRUE) # 重複あり
hist(x, breaks = 0:6) # ヒストグラム
```

### 4.3.2 一様乱数（連続）

```{r}
x <- runif(min = 0,  # 最小
           max = 1,  # 最大
           n = 1000) # 乱数の数
hist(x)
```

```{r}
x <- as.integer(      # 整数に変換
  runif(min = 1,      # 最小
        max = 7,      # 最大 + 1
        n = 1000))    # 乱数の数
hist(x, breaks = 0:6) # 結果は割愛
```

### 4.3.3 二項乱数

```{r}
n <- 100
p <- 0.5
r <- 10000
x <- rbinom(size = n, # 試行回数
            prob = p, # 確率
            n = r)    # 乱数の数
hist(x, breaks = max(x) - min(x))
```

### 4.3.4 正規乱数

```{r}
r <- 10000
x <- rnorm(mean = 50, # 平均
           sd = 5,    # 標準偏差
           n = r)     # 乱数の数
hist(x, breaks = 40)
```

#### 4.3.4.1 補足：不偏性の具体例

```{r}
library(tidyverse)

f <- function(k) {
  n <- 10000
  tmp <- replicate(n = n, expr = g(rnorm(n =  k, sd = 3)))
  list(k = k,
       mean = mean(tmp),       # 平均
       se = sd(tmp) / sqrt(n)) # 標準誤差
}
```

```{r}
g <- var
c(10, 20, 30) %>% map_dfr(f)
#> # A tibble: 3 x 3
#>       k  mean     se
#>   <dbl> <dbl>  <dbl>
#> 1    10  8.98 0.0427
#> 2    20  8.97 0.0288
#> 3    30  9.03 0.0233
```

```{r}
g <- sd
c(5, 10, 15, 20) %>% map_dfr(f)
#> # A tibble: 3 x 3
#>       k  mean      se
#>   <dbl> <dbl>   <dbl>
#> 1    10  2.92 0.00701
#> 2    20  2.95 0.00481
#> 3    30  2.97 0.00394
```

```{r}
g <- function(x) {
  n <- length(x)
  sd(x) *
    sqrt((n - 1) / 2) *
    gamma((n - 1) / 2) /
    gamma(n / 2)
}
c(10, 20, 30) %>% map_dfr(f)
#> # A tibble: 3 x 3
#>       k  mean      se
#>   <dbl> <dbl>   <dbl>
#> 1    10  3.00 0.00717
#> 2    20  2.99 0.00488
#> 3    30  3.00 0.00396
```

